In [8]:
import numpy as np

In [15]:
print(np.cos(np.pi))
print("")
print(np.log(np.exp(2.5)))
print("")
print(np.linspace(0,10,10).reshape(2,5))


-1.0

2.5

[[ 0.          1.11111111  2.22222222  3.33333333  4.44444444]
 [ 5.55555556  6.66666667  7.77777778  8.88888889 10.        ]]


In [16]:
mat_a = np.array([[3,4,5],[1,2,3],[3,5,6]])

In [18]:
mat_b =  np.linalg.inv(mat_a)

In [19]:
print(np.matmul(mat_a,mat_b))

[[ 1.00000000e+00  2.22044605e-16 -1.11022302e-16]
 [-3.33066907e-16  1.00000000e+00  1.11022302e-16]
 [-6.66133815e-16 -4.44089210e-16  1.00000000e+00]]


In [20]:
vec = np.array([1,2,3])

In [22]:
mat_c = np.matmul(mat_a,vec)

In [23]:
mat_c

array([26, 14, 31])

np.random.rand(5,2)

In [24]:
np.random.randn(5,2)

array([[-1.18774674,  0.39319639],
       [ 0.85805331,  0.52695585],
       [-0.74030151,  0.35345633],
       [-0.28707228, -0.19820551],
       [ 0.93076003, -0.18018756]])

In [25]:
np.random.rand(5,2)

array([[0.02333887, 0.9135618 ],
       [0.56380905, 0.44154544],
       [0.98278115, 0.03905729],
       [0.9689864 , 0.34193679],
       [0.76306521, 0.42721128]])

In [31]:
np.zeros([2,10]).reshape(20,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [37]:
np.linalg.solve(mat_a,mat_c)

array([1., 2., 3.])

In [41]:
vec_a = np.random.randn(10000)

In [43]:
np.max(vec_a)

3.6331758717225484

In [44]:
np.min(vec_a)

-3.5612254771298444

In [45]:
np.mean(vec_a)

-3.82394694722592e-06

In [46]:
np.std(vec_a)

1.0095545099876158

In [47]:
np.save('test_vec_a',vec_a)

In [49]:
loaded_vec = np.load('test_vec_a.npy')

In [50]:
loaded_vec

array([-1.37606607, -2.06796475, -0.43527774, ...,  0.14375514,
       -0.89498273,  0.22047159])